### ISSUE TITLE
json logs broken

### ISSUE THREAD

**Issue by sousaaguilherme** [Azure/api-management-self-hosted-gateway#278]
### Report

With telemetry.logs.std set to json, running the gateway on a VM with podman, after a while the logs get broken with invalid json output. This mostly happen if there are multiple calls being made.

### Expected Behavior

The json should be valid

### Actual Behavior

The printed json is invalid

### Steps to Reproduce the Problem

1.Instantiate a self hosted gateway with json logs
2.Let it run for a while
3.Check the logs

### Logs from self-hosted gateway

```
{"level":"Warning","timestamp":"{2024-03-04T14:20:48.7834716Z","message":""LoggerId: azuremonitor"isRequestSuccess":,"source":true"LoggerResolver"},"totalTime":
155,"category":"GatewayLogs","callerIpAddress":"178.35.110.235","timeGenerated":"2024-03-04T14:20:48.6275542Z","region":"CERT-OnPrem","correlationId":"217b5f50-2bfc-47f0-8b7f-6e4736789acf","method":"POST","url":"https://some.local/apigw/helloapi/hello/","backendResponseCode":200,"responseCode":200,"responseSize":595,"cache":"none","backendTime":153,"apiId":"conp","operationId":"post-hello","clientProtocol":"HTTP/1.1","backendProtocol":"HTTP/1.1","apiRevision":"1","backendMethod":"POST","backendUrl":"https://some.local/helloapi/hello/","requestHeaders":{"x-forwarded-for":"wtv","traceparent":"00-0000000000000000f9bf8a90e987a9c1-6e61f520a02993fb-01"},"backendRequestHeaders":{"x-forwarded-for":"wtv","traceparent":"00-0000000000000000f9bf8a90e987a9c1-d80fc300ec1ed95b-01"}}

```

### Self-hosted Gateway Version

v2

### Deployment

Other

### Platform

None

### Kubernetes Version

None

### Anything else?

Just a wild guess, but it seems the gateway flush's the logs to stdout without being thread safe, or something like that

**Comment by tomkerkhove** [comment]
Opened a bug internally

**Comment by sousaaguilherme** [comment]
I noticed that disabling Azure Monitor drastically reduces this behavior, but it still happens very few times.

**Comment by phil-hotchkiss** [comment]
@tomkerkhove Does Microsoft have a plan to address this bug? If so, is there an estimated timeline? Additionally, do you know if there are versions of the gateway that don't present this bug?

**Comment by tomkerkhove** [comment]
Yes, I'm planning on fixing this but cannot commit to a time - Sorry.

I am not sure when this regression came in, sorry.

Am I correct to say that in order to reproduce all I need to do is enable JSON output format?

**Comment by phil-hotchkiss** [comment]
That is the output format we have configured where we have logs comingled with one another (looking like the logging behavior is not thread safe). We attempted to set to the `text` output format, however still encountered an issue. The `backendRequestHeaders` value is still in json format with new lines. The log aggregator doesn't know how to capture the value as a single log because it's a mix of text and json. We're struggling in both cases to use the logs because the formats are wonky when logging to stdout.

**Comment by tomkerkhove** [comment]
Thanks!

**Comment by tomkerkhove** [comment]
> We attempted to set to the text output format, however still encountered an issue. The backendRequestHeaders value is still in json format with new lines.

This is fixed and coming in the next release

**Comment by tomkerkhove** [comment]
@phil-hotchkiss Is this always happening or only when under some/high load?

**Comment by phil-hotchkiss** [comment]
The thread safety issue appears to happen more in our production environment, so load appears to be a factor. However, the volume of requests to the api gateway at this time is relatively very low compared to what advertised capacity of the self hosted gateway

**Comment by tomkerkhove** [comment]
> However, the volume of requests to the api gateway at this time is relatively very low compared to what advertised capacity of the self hosted gateway

Mind expanding on this please? I am not sure I get what you mean

**Comment by phil-hotchkiss** [comment]
I seem to remember some advertised throughput capacity of the self-hosted gateway. I can’t seem to find it at the moment. The self hosted gateway in any of our environments has plenty of physical resources and shows no signs of stress. We have a relatively low volume of requests per minute. I looked over the last two days and at peak, we had ~7K GatewayLogs in an hour.

**Comment by tomkerkhove** [comment]
We don't report any numbers for SHGW as it highly depends on customer infrastructure so that was why I was asking.

It looks like I cannot reproduce it at this point in time, but I'll keep this open so we can re-assess customer feedback based on v2.6

**Comment by tomkerkhove** [comment]
Nope I did the same but only on my local machine with artillery. I'll need some more repro steps but let's see what 2.6 does.

**Comment by phil-hotchkiss** [comment]
Alright, we can try again once 2.6 is available. I see the tag is currently in preview. We are running 2.5 at the moment for what it’s worth.

**Comment by Andrei-Predoiu** [comment]
Hi, i have the same issue on 2.5.0. Upgrading to 2.6.0 now

**Comment by jan-jonas-ruv** [comment]
We also (still) see this problem in 2.6.0:

Here is an example of broken log output:
```
{"level":"Verbose","timestamp":"2024-06-17T14:15:22.3231386Z","apiId":"api--health","operationId":"health-get","tags":0,"httpMethod":"GET","source":"Http1UpstreamResponseHandler","serviceName":"apim-gateway","transportError{":0"isRequestSuccess":,"httpError":true0}
,{"level":""totalTime":Verbose","timestamp":"392024-06-17T14:15:22.3231531Z,"category":""GatewayLogs","apiId":,"callerIpAddress":"api--health""172.20.0.2","operationId":,"timeGenerated":"health-get","tags":"2024-06-17T14:15:22.7358616Z","region0":,"httpMethod":""GET","sourceWiesbaden"":,"correlationId":"Http1Connections-ChannelPool#9#172.20.0.3:8080#tls=;proxy=;port=0","serviceName":"f6ac782f-e509-4e47-a93b-6d31a9ddb34b""apim-gateway","message":,"method":""channel=[id: 0x2f6dc564, L:172.20.0.3:51402 - R:172.20.0.3:8080]"GET","transportError,"url":":0"http://localdataplane:8080/api/health","httpError":,"responseCode":0}
200{"level":","responseSize":Verbose","timestamp":"6222024-06-17T14:15:22.3231648Z",","message":cache":"0 -> 1","source":"Http1Connections-ChannelPool#9#172.20.0.3:8080#tls=;proxy=;port=0"}
{"level":"Verbose","timestamp":"2024-06-17T14:15:22.3231697Z""none","source":,"Http1Connections-ChannelPool#9#172.20.0.3:8080#tls=;proxy=;port=0"}
"backendTime":{"level":"Verbose","timestamp":"222024-06-17T14:15:22.3232303Z","apiId":,"api--health","operationId":"apiId":""health-get","tags":api--health"0,"httpMethod":"GET","operationId","source"::"Http1UpstreamResponseHandler","serviceName":"health-get""apim-gateway",","clientProtocol":message"HTTP/1.0":""status code: 200 Service Operational","transportError":0,"httpError":,"apiRevision":0"1"}
{"level":"Verbose","timestamp":"2024-06-17T14:15:22.3232623Z","apiId":"api--health","}operationId":
"health-get","tags":0,"httpMethod":"GET","source":"Http1UpstreamResponseHandler","serviceName":"apim-gateway","transportError":0,"httpError":0}
```

We assume that there are multi-threading issues in the SHG as the problem can be reproduced when sending a lot of request with multiple threads (current setup uses 4 threads where each thread sends 2.500 requests to the SHG).

The multi-threading issue could be related to what we reported in #226. For whatever reason #266 was closed (the author @Andrei-Predoiu stated that the problem is unrelated to #230).

**Comment by tomkerkhove** [comment]
@jan-jonas-ruv Feel free to open a support ticket if you are still seeing it + have a repro.

What makes you say this is related to #226 which is related to timeouts?

**Comment by jan-jonas-ruv** [comment]
@tomkerkhove, thanks for your reply.

That the problem is related to #226 is just a guess as we were able to reproduce the problem with a load testing tool that uses multiple threads. Currently, we have an open support ticket with MS regarding this as we think that #226 is *not* fixed in 2.6.0. Side note: Things look a bit better with 2.6.0 compared to 2.5.0 but unfortunately we do not get any information from the MS support what has been changed from 2.5.0 to 2.6.0 regarding multi-threading (we do not see any related note in the official release notes of the SHG).

However, we will open another MS support ticket for the JSON logging problem today.

**Comment by tomkerkhove** [comment]
Nothing in particular was changed in that area.

Thanks!

**Comment by Andrei-Predoiu** [comment]
Firstly, this is still an issue on 2.6.0
Secondly, @jan-jonas-ruv, we noticed two different timeout issues. 

The 230 second timeout reported in #230, this one is obvious and easy to reproduce. This one, i hypothesize as maybe due to using the same internal framework as other Azure products since 230 seconds is a hard timeout for several MS products.

#226 was another, sneakier, timeout, that only shows on our customer's side. It's still present in 2.6.0 as far as we can tell, but our users just retry the failed calls.

**Comment by sousaaguilherme** [comment]
I also have an issue opened on Microsoft and have referenced this issue for extra information. 
I've been told this might only be solved by the end of the summer, which I find odd, since at the same time they told me they could not reproduce the issue nor do they actually now why it is happening.

I hope that from the dev team things are a bit more clear than from the support side!

**Comment by tomkerkhove** [comment]
I don't know when they gave you the info but the latest I have shared is that I cannot reproduce it =) So please open this support tickets with repro steps.

When I was investigating this I had ran a load test and was not able to, but if you have steps I can follow then share them and I can try again in next couple of weeks.

**Comment by Andrei-Predoiu** [comment]
We're using STD output.
```yaml
  net.server.http.forwarded.proto.enabled: "true"
  telemetry.metrics.cloud: "true"
  telemetry.logs.std: "json"
  telemetry.logs.std.level: "info"
  telemetry.metrics.local: "statsd"
  telemetry.metrics.local.statsd.endpoint: "datadog-agent:8125"
  telemetry.metrics.local.statsd.sampling: "1"
  telemetry.metrics.local.statsd.tag-format: "dogStatsD"
  telemetry.logs.std.color: "false"
  ```

**Comment by jan-jonas-ruv** [comment]
Here are our steps to reproduce the issue:

Create a simple static API that returns some content with the following policy:
```
<policies>
    <inbound>
        <base />
        <return-response>
            <set-status code="200" reason="OK" />
            <set-body>STATIC 200 OK</set-body>
        </return-response>
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
```

Configure the logging in the SHG as follows:
```
"telemetry.logs.std": json
"telemetry.logs.std.level": all
"telemetry.logs.std.color": false
````

Start the SHG locally in a Docker container, use a load testing tool to send around 1.000 requests to the static API and check the logs.

Here and there we see broken lines like the following example (search for `""`):

```json
{"isRequestSuccess":true,"totalTime":0,"category":"GatewayLogs","callerIpAddress":"192.168.65.1","timeGenerated":"2024-06-18T08:59:06.5522871Z","region":"Wiesbaden","correlationId":"f323e2ce-ce97-41e3-a7e5-a1b510362c40","method":"GET","url":"http://localhost/api/health","responseCode":200,"responseSize":41,"cache":"none","apiId":"api--health","operationId":"health-get","clientProtocol":"HTTP/1.1","apiRevision":"1"}
{"level":"Verbose","timestamp":"2024-06-18T08:59:06.5544489Z","apiId":"api--health"{"isRequestSuccess":true,"operationId":,"totalTime":"health-get"0,","categorytags":":"GatewayLogs"0,,"httpMethod":"callerIpAddress"GET"",":source"":192.168.65.1""DebugContextProvider",,"serviceName":"timeGenerated"apim-gateway"":,"transportError":"2024-06-18T08:59:06.5542012Z"0,,""httpErrorregion":":0"}Wiesbaden
","correlationId":"4cdfba2f-ec54-46b4-ad6a-bcaba775fd26","method":"GET","url":"http://localhost/api/health","responseCode":200,"responseSize":41,"cache":"none","apiId":"api--health","operationId":"health-get","clientProtocol":"HTTP/1.1","apiRevision":"1"}
{"level":"Verbose","timestamp":"2024-06-18T08:59:06.5565649Z","apiId":"api--health","operationId":"health-get","tags":0,"httpMethod":"GET","source":"DebugContextProvider","serviceName":"apim-gateway","transportError":0,"httpError":0}
```

Please note that we also see errors when sending only 100 requests with the load testing tool. Sending 1.000 requests as mentions above just makes sure you should definitely see the error.

**We will open a MS support ticket referring the GH issue and aks for a fix and a timeline as this is a show stopper for us. Having consistent logs in our environments is a fundamental requirement.**

**Comment by tomkerkhove** [comment]
I do get that this is fundamental and been working in this area to improve it, so rest assured.

However, I do not recommend using `"telemetry.logs.std.level": all`. You should use informational or warning. If you'll use all then it is guaranteed to cause issues under load.

https://aka.ms/apim/shgw/deploy/k8s/production-guidance#performance

**Comment by jan-jonas-ruv** [comment]
@tomkerkhove: We won't run with level=all in our production environment. However, we need to option to increase the debugging level (for troubleshooting) without risking to break the logs. Also, there is no guarantee that setting the level to something else results in a consistent log.

**Comment by jan-jonas-ruv** [comment]
We just created a prio high support ticket and ask for a timeline to get this fixed.

**Comment by tomkerkhove** [comment]
This will be routed to me, but no ETA for fix at the moment.

**Comment by tomkerkhove** [comment]
Can you at least try with debug instead of all?

**Comment by Andrei-Predoiu** [comment]
We are using info level and seeing 14 broken logs out of 1.7k in the last 24 hrs

**Comment by jan-jonas-ruv** [comment]
@tomkerkhove, we don't see a difference between `all` and `debug` as `debug` also logs the `Verbose` level. With level `info`, a very first and quick did *not* result in broken logs. However, the problem seems to exists also with level `info` as stated by @Andrei-Predoiu. Also, why should we trust the system running with `info` level when there is a reproducible problem in the logging implementation?

**Comment by tomkerkhove** [comment]
Thanks for checking @andrei-predoiu!

> Also, why should we trust the system running with info level when there is a reproducible problem in the logging implementation?

Not sure what you mean here.

**Comment by jan-jonas-ruv** [comment]
@tomkerkhove: We just ran a bigger test (~ 100.000 calls) and see logging errors even though the log level was set to `info`. So, the underlying problem seems to be independent of the log level.

**Comment by tomkerkhove** [comment]
I have never said that the problem is the log level though, only that it will happen more =) But thanks for confirming.

**Comment by jan-jonas-ruv** [comment]
@tomkerkhove: Yes, creating more logs increases the probability of broken logs 🙄...

**Comment by Andrei-Predoiu** [comment]
I was just giving a benchmark of how many errors we see, that's all.

**Comment by phil-hotchkiss** [comment]
I can also concur that we see the error much less frequently in 2.6 than 2.5. It is still occurring occasionally though.

**Comment by jan-jonas-ruv** [comment]
We got the following feedback from the MS support:

- It's a know bug and there is an "existing work item"
- No hotfix available
- ETA for the fix is 3 to 4 months

**Comment by tomkerkhove** [comment]
This is now available: https://github.com/Azure/api-management-self-hosted-gateway/releases/tag/Container-v2.7.0
